[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
url = { version = "2.3.1", features = ["serde"] }
scale = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }

# dependencies for extrinsics (deploying and calling a contract)
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
sp-core = "20.0.0"
sp-runtime = "23.0.0"
sp-weights = "19.0.0"
pallet-contracts-primitives = "23.0.0"
scale-info = "2.7.0"
subxt = "0.28.0"
hex = "0.4.3"
jsonrpsee = { version = "0.18.2", features = ["ws-client"] }

