#Test config file

contract_path = "src/substrate/contract/ink/testcontract.contract"
toml = "src/substrate/contract/ink/Cargo.toml"
url = "ws://127.0.0.1:9944"
contract_address = "5CVEunQyTTDR6zKqCKLubHVrLaHB2S7Dma1bn73Lhj24RMbb"