name: Build core
description: Build core
inputs:
  profile:
    description: "The `--profile` of cargo build"
    required: true
    default: "testnet"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install_toolchain
    - name: Build core blockchain
      run: cargo build -vv --profile ${{ inputs.profile }}
      shell: bash
