name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master # https://github.com/easimon/maximize-build-space
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 1024
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/build-core